version: '3'
services:
  xperience:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: password_123
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    restart: always
